title: Faiza Iqbal
# logo: /assets/img/profile-pic (1).png
description: >
  I am a masters student of Data Science at Mehran University of Engineering nad Technology. I completed my Bachelors in Telecommunications Engineering. 
  I specialize in managing complex data and developing innovative solutions, such as a university website for optimizing data handling. My research 
  focuses on linguistic features and explainable AI in Alzheimer’s dementia. With expertise in Python, machine learning, and SQL Server, I hold the 
  highest GPA in my Master’s program and co-authored a chapter on AI-enabled 6G mobile systems. You can contact me via email or LinkedIn.

theme: jekyll-theme-minimal
