title: Faiza Iqbal
logo: /assets/Faiza.jpeg
description: >
  I am a masters student of Data Science at Mehran University of Engineering nad Technology. I completed my Bachelors in Telecommunications Engineering. 
  I specialize in managing complex data and developing innovative solutions, such as a university website for optimizing data handling. My research 
  focuses on linguistic features and explainable AI in Alzheimer’s dementia. With expertise in Python, machine learning, and SQL Server. You can 
  contact me via email or LinkedIn.







  

theme: jekyll-theme-minimal
